In [1]:
import numpy as np
import cvxpy as cp
import matplotlib.pyplot as plt

###Implementation of the paper "Fast linear iterations for distributed averaging" by Xiao and Boyd.

In [2]:
#what is vec(1)*vec(1)^T/n? Say n = 10.
vec_ones = np.ones((10,1))
vec_ones_matrix = vec_ones @ vec_ones.T/10
print(vec_ones_matrix)

[[0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]]


The network we are considering for this is:

<img src="network_prac.jpg" alt="drawing" width="400"/>

In [4]:
"""For this network, the number of nodes is n = 7, so the matrix W has to converge to vec(1)*vec(1)^T/7 for the network 
to converge to average the values of the nodes."""

conv_matrix = vec_ones @ vec_ones.T/7

In [ ]:
#solving a simple optimization problem
