In [2]:
import numpy as np
from scipy import integrate,linalg,optimize
import matplotlib.pyplot as plt

In [3]:
class statespace:
    def __init__(self, A, B, C, D):
        self.A = A
        self.B = B
        self.C = C
        self.D = D

    def xdot(self, x, u):
        return self.A @ x + self.B @ u

    def output(self, x, u):
        return self.C @ x + self.D @ u
    
    def xintegrate(self, x, u, dt):
        return integrate.solve_ivp(self.xdot, [0, dt], x0)

In [ ]:
sys1 = statespace(np.array([[0, 1], [0, 0]]), np.array([[0], [1]]), np.array([[1, 0]]), np.array([[0]]))

sys1.xdot(np.array([0, 0]), 1)

In [ ]:
def xdot(x):
    return A@x

xint  = integrate.solve_ivp(xdot,)

In [38]:
def func(A,B,x,u):
    return np.array(A@x + u * B).reshape(2,) 

A = np.random.rand(2,2)
B = np.random.rand(2,1)
print(A,'\n',B)
x0 = np.random.randn(2)
u = np.random.rand()
print(x0,u)

[[0.66408272 0.46696765]
 [0.49446827 0.62835853]] 
 [[0.92147383]
 [0.33221397]]
[-0.78051087  0.68129032] 0.42392875233270355


In [44]:
print(A@x0)
print(np.shape(A@x0))
print(B*u)
print(np.shape(B*u))
print(np.array(A@x0 + B* u))
print(np.shape(A@x0 + B*u))

[-0.20018324  0.04215673]
(2,)
[[0.39063925]
 [0.14083505]]
(2, 1)
[[ 0.19045601  0.43279598]
 [-0.05934819  0.18299178]]
(2, 2)


In [53]:
#trying out these pesky broadcast rules
A = np.random.rand(2,2)
B = np.random.rand(2,1)
print(A)
print(B)
print(A + B)

[[0.58334729 0.44696936]
 [0.78952917 0.54370864]]
[[0.01228343]
 [0.80089953]]
[[0.59563073 0.45925279]
 [1.59042871 1.34460817]]


In [30]:
integral = integrate.solve_ivp(func, t_span=[0,10],y0 = x0, t_eval= np.linspace(0,10,1000),args=(A,B))

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)